name: userland_commands
description: Userland commands for Monolith
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  meta: ^1.7.0
  path: ^1.8.0
  glob: ^2.1.0
  common:
    path: ../common